config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about',as:'about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources:items,only:[:index,:show]
    resource:customers,only:[:update]
    resources:cart_items,only:[:index,:update,:destroy,:destroy_all,:create]
    resources:orders,only:[:new,:confilm,:complete,:create,:index,:show]
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]
  end
  # 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    get 'homes/about' => 'homes#about',as:'about'
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
    resources :genres,only:[:index,:create,:edit,:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :orders,only:[:show,:update]
    resources :order_details,only:[:update]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
     render "edit"
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer.id)
  end

  private
  def customer_params
    params.permit(:last_name, :frist_name, :last_name_kana ,:frist_name_kana, :postal_code, :address, :telephone_number, :is_deleted, :email)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    genre = Genre.new(genre_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    genre.save

    redirect_to admin_genres_path
  end

  def edit
    @genres = Genre.find(params[:id])
    render "edit"
  end

  def update
    @genres = Genre.find(params[:id])
    @genres.update(genre_params)
    redirect_to admin_genres_path
  end


  def genre_params
  params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
     @item = Item.new
  end

  def create
     @items = Item.new(item_params)
     @items.save
     redirect_to admin_item_path(@items)

  end

  def index
    @item=Item.new
    @items=Item.all

  end

  def show
    @item=Item.find(params[:id])
    @items=Item.new
  end

  def edit
    @item = Item.find(params[:id])

  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id ,:price, :is_active, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
   @customer = Customer.find(params[:id])
   @order = Order.find(parms[:id])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h1>会員情報編集</h1>


<%= form_with model: @customer, url: admin_customer_path, method: :PATCH do |f| %>
<div class="form-group">
  <label for="customer_id">会員ID</label>
  <br><%= @customer.id %>
<div class="form-group">
  <label for="customer_last_name">氏名</label>
  <br><%= f.text_area :last_name %>
</div>
<div class="form-group">
  <label for="customer_last_name_kana">フリガナ</label>
  <br><%= f.text_area :last_name_kana %>
</div>
<div class="form-group">
  <label for="customer_postal_code">郵便番号</label>
  <br><%= f.text_area :postal_code %>
</div>
<div class="form-group">
  <label for="customer_address">住所</label>
  <br><%= f.text_area :address %>
</div>
<div class="form-group">
  <label for="customer_telephone_number">電話番号</label>
  <br><%= f.text_area :telephone_number %>
</div>
<div class="form-group">
  <label for="customer_email">メールアドレス</label>
  <br><%= f.text_area :email %>
</div>
<div class="form-group">
  <label for="customer_is_deleted">会員ステータス</label>
  <br><%= f.text_area :is_deleted %>
</div>
  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/customers/index.html.erb
<main>
  <p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

<div class="col-md-8 offset-md-1">
    <h2 class="mt-3">会員一覧</h2>
    <table class="table table-hover table-inverse">
      <thead>
       <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
          <th colspan="3"></th>
        </tr>
       </thead>
      <tbody>
           <% @customer.each do |customer| %>
         <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.last_name,admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td><%= customer.is_deleted %></td>
         </tr>
           <% end %>
      </tbody>
     </table>
    </div>
   </div>
  </div>
 </miain>

app/views/admin/customers/show.html.erb
<div class="col-md-8 offset-md-1">
  		<h2>会員詳細</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
  		      <td>
  		         <%= @customer.last_name %>
  		      </td>
  		      <td>
  		         <%= @customer.created_at %>
  		      </td>
  		      <td>
  		         <%= @customer.last_name_kana %>
  		      </td>
  		      <td>
  		         <%= @customer.postal_code %>
  		      </td>
  		      <td>
  		         <%= @customer.address %>
            </td>
            <td>
  		         <%= @customer.telephone_number %>
            </td>
            <td>
  		         <%= @customer.email %>
            </td>
            <td>
  		         <%= @customer.is_deleted %>
            </td>

  		    </tr>
  		    <td>
                 <%= link_to "編集する", edit_admin_customer_path(@customer) %>
          </td>
          <td>
                 <%= link_to "注文履歴一覧を見る", admin_root_path(@customer) %>
          </td>
        </tbody>
      </table>
</div>