config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about',as:'about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources:items,only:[:index,:show]
    resource:customers,only:[:update]
    resources:cart_items,only:[:index,:update,:destroy,:destroy_all,:create]
    resources:orders,only:[:new,:confilm,:complete,:create,:index,:show]
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]
  end
  # 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    get 'homes/about' => 'homes#about',as:'about'
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
    resources :genres,only:[:index,:create,:edit,:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :orders,only:[:show,:update]
    resources :order_details,only:[:update]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    genre = Genre.new(genre_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    genre.save

    redirect_to admin_genres_path
  end

  def edit
    @genres = Genre.find(params[:id])
    render "edit"
  end

  def update
    @genres = Genre.find(params[:id])
    @genres.update(genre_params)
    redirect_to admin_genres_path
  end


  def genre_params
  params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
     @item = Item.new
  end

  def create
     @items = Item.new(item_params)
     @items.save
     redirect_to admin_item_path(@items)

  end

  def index
    @item=Item.new
    @items=Item.all

  end

  def show
    @item=Item.find(params[:id])
    @items=Item.new
  end

  def edit
    @item = Item.find(params[:id])

  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id ,:price, :is_active, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
   @customer = Customer.find(params[:id])
   @order = Order.find(parms[:id])
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
  #   super
  #end

  # POST /resource/sign_in
  #def create
  #   super
  #end

  # DELETE /resource/sign_out
  #def destroy
  #   super
  #end

  # protected
  protected
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model: @genres, url: admin_genre_path(@genres), method: :PATCH do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>

  <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>

<%= form_with model: @genre, url: admin_genres_path do |f| %>

<div class="form-group">
  <tbosy>
    <tr>
       <td>
        <label for="genres">ジャンル名</label>
         <br><%= f.text_field :name %>
          </div>
          <div class="form-group">
           <%= f.submit '新規登録' %>
           <% end %>

          </div>
       </td>
    </tr>
  </tbody>

<% @genres.each do |genre| %>
<%= genre.name %>
<%= link_to "編集する", edit_admin_genre_path(genre) %>
<% end %>
<td>

</td>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>


<%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
  <h4>商品画像</h4>
    <%= f.file_field :profile_image, placeholder: "ファイル選択", accept: "image/*" %>
  <h4>商品名</h4>
    <%= f.text_field :name %>
  <h4>商品説明</h4>
    <%= f.text_area :introduction %>
  <h4>ジャンル</h4>
    <%= f.label :genre_id %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>

  <h4>税抜価格</h4>
    <%= f.text_area :price %>
  <h4>販売ステータス</h4>
    <%= f.radio_button :is_active, true%>
    <%= f.label :is_active_true, "販売中" %>
    <%= f.radio_button :is_active, false %>
    <%= f.label :is_active_false, "販売停止中" %>

  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/items/index.html.erb
<div class="col-md-8 offset-md-1">
    <h2 class="mt-3">商品一覧</h2>
    <table class="table table-hover table-inverse">
      <thead>
       <tr>
          <th></th>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
          <th></th>
          <th colspan="3"></th>
        </tr>
       </thead>
      <tbody>
           <% @items.each do |item| %>
         <tr>
          <td></td>
          <td><%= item.id %></td>
          <td><%= link_to item.name,admin_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active %>
            販売中
            <% else %>
            販売停止中
            <% end %>
          </td>
          <td></td>
         </tr>
           <% end %>
      </tbody>
     </table>
</div>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>


    <%= form_with model: @item, url: admin_items_path, method: :POST do |f| %>
  <h4>商品画像</h4>
    <%= f.file_field :image, accept: "image/*" %>
  <h4>商品名</h4>
    <%= f.text_field :name %>
  <h4>商品説明</h4>
    <%= f.text_area :introduction %>
  <h4>ジャンル</h4>
    <%= f.label :genre_id %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>

  <h4>税抜価格</h4>
    <%= f.text_area :price %>
  <h4>販売ステータス</h4>
    <%= f.radio_button :is_active, true%>
    <%= f.label :is_active_true, "販売中" %>
    <%= f.radio_button :is_active, false %>
    <%= f.label :is_active_false, "販売停止中" %>

  <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<div class="col-md-8 offset-md-1">
  		<h2>商品詳細</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
  		      <td>
  		        <% if @item.image.attached? %>
              <%= image_tag @item.image, size: "300x300" %>
              <% else %>
              <%= image_tag 'no_image', size: "300x300" %>
              <% end %>
  		      </td>
  		      <td>
  		         <%= @item.name %>
  		      </td>
  		      <td>
  		         <%= @item.introduction %>
  		      </td>
  		      <td>
  		         <%= @item.genre_id %>
  		      </td>
  		      <td>
  		         <%= @item.price %>
              </td>
              <td>
  		         <%= @item.is_active %>
              </td>

  		    </tr>
  		    <td>
                 <%= link_to "編集する", edit_admin_item_path(@item) %>
            </td>
        </tbody>
      </table>
</div>

app/views/admin/orders/show.html.erb
<div class="col-md-8 offset-md-1">
  		<h2>注文履歴詳細</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
  		      <td>
  		         <%= @customer.last_name %>
  		      </td>
  		      <td>
  		         <%= @order.created_at %>
  		      </td>
  		      <td>
  		         <%= @order.address %>
  		      </td>
  		      <td>
  		         <%= @order.payment_method %>
  		      </td>
  		      <td>
  		         <%= @order.status %>
            </td>
  		    </tr>

        </tbody>
      </table>
</div>