config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about',as:'about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources:items,only:[:index,:show]
    resource:customers,only:[:update]
    resources:cart_items,only:[:index,:update,:destroy,:destroy_all,:create]
    resources:orders,only:[:new,:confilm,:complete,:create,:index,:show]
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]
  end
  # 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    get 'homes/about' => 'homes#about',as:'about'
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
    resources :genres,only:[:index,:create,:edit,:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :orders,only:[:show,:update]
    resources :order_details,only:[:update]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    genre = Genre.new(genre_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    genre.save

    redirect_to admin_genres_path
  end

  def edit
    @genres = Genre.find(params[:id])
    render "edit"
  end

  def update
    @genres = Genre.find(params[:id])
    @genres.update(genre_params)
    redirect_to admin_genres_path
  end


  def genre_params
  params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
     @item = Item.new
  end

  def create
     @items = Item.new(item_params)
     @items.save
     redirect_to admin_item_path(@items)

  end

  def index
    @item=Item.new
    @items=Item.all

  end

  def show
    @item=Item.find(params[:id])
    @items=Item.new
  end

  def edit
    @item = Item.find(params[:id])

  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id ,:price, :is_active, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<html>

  <head>
    <title>Cake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span></span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li>
               <%= link_to customers_my_page_path,class: "nav-link text-light" do %>
                <i class="fas fa-home"></i>マイページ
               <% end %>
              </li>
              <li>
              <%= link_to items_path,class: "nav-link text-light" do %>
                <i class="fas fa-users"></i>商品一覧
              <% end %>
              </li>
              <li>
              <%= link_to cart_items_path,class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i>カート
              <% end %>
              </li>
              <li>
              <%= link_to destroy_customer_session_path, method: :delete,class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li>
               <%= link_to admin_items_path,class: "nav-link text-light" do %>
                <i class="fas fa-home"></i>商品一覧
               <% end %>
              </li>
              <li>
              <%= link_to admin_customers_path,class: "nav-link text-light" do %>
                <i class="fas fa-users"></i>会員一覧
              <% end %>
              </li>
              <li>
              <%= link_to admin_root_path,class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i>注文履歴一覧
              <% end %>
              </li>
              <li>
              <%= link_to admin_genres_path,class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i>ジャンル一覧
              <% end %>
              </li>
              <li>
              <%= link_to destroy_admin_session_path, method: :delete,class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
              </li>
            <% else %>
              <li>
              <%= link_to about_path,class: "nav-link text-light" do %>
                <i class="fas fa-home"></i>About
              <% end %>
              </li>
              <li>
               <%= link_to items_path,class: "nav-link text-light" do %>
                <i class="fas fa-link"></i>商品一覧
              <% end %>
              </li>
              <li>
               <%= link_to new_customer_session_path,class: "nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>新規登録
              <% end %>
              </li>
              <li>
              <%= link_to new_customer_session_path,class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>ログイン
              <% end %>
              </li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


    <div class="text-success">
         <%= flash[:notice] %>
    </div>


    <%= yield %>
  </body>
  </html>
</html>